= Übungen zu Kommandos und Manpages

== Zeichenklassen

Informiert euch über das Konzept der _Brace Expansion_ in der Manpage der BASH.

=== Übung

a) Erstellt 30 Dateien mit den Namen `datei01.txt` bis `datei30.txt` mit einem einzigen Befehl. Fügt anschließend die Datei `datei2.txt` hinzu.

b) Löscht nun die Dateien `datei02.txt`, `datei12.txt` und `datei22.txt` mit einem Befehl.

c) Erstellt nun 30 Dateien nach folgendem Muster mit nur einem Befehl:

----
a01.dat bis a30.dat
b01.dat bis b30.dat
        ...
f01.dat bis f30.dat
----

== Aliase

Erstellt euch Aliase, damit die Kommandos `mv`, `rm` und `cp` _sicherer_ werden, dass also eine Nachfrage erscheint, falls eine beretis existierende Datei überschrieben_gelöscht werden soll. Sorgt dafür, dass die Aliase in einer seperaten Datei definiert werden.

Überlegt, ob ihr diese _Sicherheitseinstellungen_ als sinnvoll erachtet oder nicht, begründet eure Entscheidung und behaltet euere Konfiguration dementsprechend bei oder ändert sie wieder ab.

Überlegt euch einfach selbst noch ein paar Aliase, die euch sinnvoll erscheinen.

Ein Alias, den ich z.B. gerne verwende, sorgt dafür, dass mir bei der Eingabe von `l` der Inhalt des aktuellen Verzeichnisses untereinander anstatt spaltenbasiert ausgegeben werden, allerdings ohne zusätzliche Informationen über den Eigentümer etc.

