= Übungen zu cron und systemd-timer

== cron

a) Ersetzt die folgenden Zeitangaben durch die Spezifikation, die ansonsten in
den ersten fünf Feldern einer /crontab/ vorgenommen werden müssten:

----
| @hourly   |
| @daily    |
| @weekly   |
| @monthly  |
| @annually |
----

b) Erklärt, wann die folgenden `cronjobs` ausgeführt werden:

----
| 30 13 * * 1-5      |
| 00 09-18 * * *     |
| 30 08 1 1 *        |
| 0,20,40 11 * * Sun |
| 00 09 10-20 1-3 *  |
| */20 * * * *       |
----

c) Betrachtet folgenden `cronjob`:

----
00 13 * * 5 date
----

Wo "erscheint" die Ausgabe dieses Jobs?

d) Erstellt einen cronjob, der das Skript `foobar.sh` ein eurem
Heimatverzeichniss alle 10 Minuten ausführt und die Ausgabe in die Datei
`output.log` schreibt. Was passiert dann mit eventuell auftretenden Fehlern?

e) Untersucht die Datei `/usr/bin/crontab`. Fällt euch bei den Berechtigungen
etwas auf? Was hat das zu bedeuten?

== systemd-timer

a) Ersetzt die folgenden `OnCalendar` Abkürzungen eines Systemd Timers durch die Spezifikation, die ansonsten dort vorgenommen werden müssten:

----
| hourly  |
| daily   |
| weekly  |
| monthly |
| yearly  |
----

b) Erklärt, wann die folgenden `systemd-timer` ausgeführt werden:

----
| *-*-* 08:30:00            |
| Sat,Sun *-*-* 05:00:00    |
| *-*-01 13:15,30,45:00     |
| Fri *-09..12-* 16:20:00   |
| Mon,Tue *-*-1,15 08:30:00 |
| *-*-* *:00/05:00          |
----

